### ISSUE TITLE
The 'Note Positions' theme option doesn't work.

### ISSUE THREAD

**Issue by MrThatKid** [ListenerJubatus/smtheme-fiftyOne#17]
When choosing the 'Lower' option, it doesn't affect the y offset of the playfield.

This could be fixed by setting the ReceptorArrowsYStandard and ReceptorArrowsYReverse metrics.
Default uses a function to determine the value.

This only affects the 5.0/5.1 version, as 5.2 has an option for y offset in its' player settings.

**Comment by ListenerJubatus** [comment]
Fixed
