### ISSUE TITLE
CDtitles should be in front of banner border

### ISSUE THREAD

**Issue by Joehuu** [ListenerJubatus/smtheme-fiftyOne#24]
The draworder number needs to be changed. Made an issue instead because I don't know the number (I inputted a random number to get the picture).

![](https://puu.sh/B47c6/62a427a6d1.png) ![](https://puu.sh/B479W/78b53e8d95.png)

https://github.com/ListenerJubatus/smtheme-fiftyOne/blob/1b429c2b2d2bd2f9c2e34d830b5595eda5255d7e/BGAnimations/ScreenSelectMusic%20decorations/default.lua#L444-L448

**Comment by ListenerJubatus** [comment]
Fixed
