### ISSUE TITLE
Select Style should go away.

### ISSUE THREAD

**Issue by shakesoda** [ListenerJubatus/smtheme-fiftyOne#6]
We live in a world of AutoSetStyle, this screen is useless.

Also, select mode should switch to a horizontal scroller whenever you get to that (old SM had this right - let's just go for that)

**Comment by 1033Forest** [comment]
A better idea, would be to have it on by default (those who still want the old select style screen can re-enable it in the operator menu)

**Comment by shakesoda** [comment]
AutoSetStyle makes the screen _completely_ obsolete. It's useless and makes it take longer to get to gameplay.

**Comment by ListenerJubatus** [comment]
Resolved for a while now.
